apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-oss
parameters:
  # volumeAs is optional, should be 'filesystem' or 'subpath', default value is 'subpath'
  volumeAs: filesystem
  networkType: open
  authType: sts
  # akId: ***
  # akSecret: ***
  # bucketReclaim: retain
  
provisioner: ossplugin.csi.alibabacloud.com
reclaimPolicy: Delete