apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-csi-pv
  labels:
    alicloud-pvname: oss-csi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ossplugin.csi.alibabacloud.com
    # set volumeHandle same value pv name
    volumeHandle: oss-csi-pv
    volumeAttributes:
      bucket: "python"
      url: "oss-cn-hangzhou.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=10000 -o multipart_size=64 -o parallel_count=16 -o multireq_max=30 -o allow_other"
      akId: "***"
      akSecret: "***"
      path: "/"
      accelerate: "lvm"
      accelerateVolume: "lvm-ea293d22-0f83-11ea-afc4-00163e0a576c"